apiVersion: scheduler.kalypso.io/v1alpha1
kind: SchedulingPolicy
metadata:
  name: int-test-policy
spec:
  deploymentTargetSelector:
    workspace: kaizentm
    labelSelector:
      matchLabels:
        purpose: int-test
  clusterTypeSelector:
    labelSelector:
      matchLabels:
        type: vm
