apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: {{DEPLOYMENT_TARGET_NAME}}
  namespace: flux-system-ghjgjh
spec:
  interval: 1m0s
  url: {{DEPLOYMENT_TARGET_REPO}}
  ref:
    branch: {{DEPLOYMENT_TARGET_ENVIRONMENT}}
  secretRef:
      name: repo-secret    
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: {{DEPLOYMENT_TARGET_NAME}}
  namespace: flux-system
spec:
  interval: 1m0s
  targetNamespace: {{DEPLOYMENT_TARGET_NAMESPACE}}
  sourceRef:
    kind: GitRepository
    name: {{DEPLOYMENT_TARGET_NAME}}
  path: {{DEPLOYMENT_TARGET_PATH}} 
  prune: true