apiVersion: v1
kind: ConfigMap
metadata:
  name: restricted-config
  labels:
     platform-config: "true"
     restricted: "false"
data:
  DATABASE_URL: mysql://restricted-host:3306/mysqlrty999000078698gfghfgfgsdf
