name: cd

on:
  workflow_dispatch:
    inputs:
      promoted_commit_id:
        description: 'Promoted Commit Id from Main'
        required: true
        type: string
      environment:
        required: true
        type: string
  
jobs:
  promote_to_environment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2.3.4

    - name: Save Promoted Commit Id 
      run: |
        echo "$COMMIT_ID" > Promoted_Commit_Id
      env:
        COMMIT_ID: ${{ inputs.promoted_commit_id }}

    - name: Push Promoted Commit Id to GitOps repo
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GITOPS_REPO_TOKEN }}
      with:
        source_file: 'Promoted_Commit_Id'
        destination_repo: ${{ secrets.GITOPS_REPO }}
        destination_folder: '.github/tracking'
        destination_branch: ${{ inputs.environment }}
        user_email: 'agent@gitops.com'
        user_name: 'Git Ops'
        commit_message: 'Promoting Commit_Id from the control plane'

    - name: Update Commit Status
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          /repos/$GITHUB_REPOSITORY/statuses/$PROMOTED_COMMIT_ID \
          -f state='pending' \
        -f target_url='' \
        -f description="Promoted" \
        -f context="$ENVIRONMENT environment" 
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PROMOTED_COMMIT_ID: ${{ inputs.promoted_commit_id }}
        ENVIRONMENT: ${{ inputs.environment }}

  
  transform:
    needs: promote_to_environment
    uses: ./.github/workflows/transform.yaml
    with:
      promoted_commit_id: ${{ inputs.promoted_commit_id }}
      environment: ${{ inputs.environment }}
    secrets: inherit
