name: cd

on:
  workflow_call:
    inputs:
      promoted_commit_id:
        description: 'Promoted Commit Id from Main'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        required: true
        type: string
  
# env:
#   TRACKING_FOLDER: 0.0.1
#   APP_NAME: rancher-hello-world
#   WORKSPACE_NAME: coral-applications 
#   IMAGE_NAME: ${{ secrets.IMAGE_NAME }} 

jobs:
  promote_to_environment:
    runs-on: ubuntu-latest
    steps:
    - name: Save Promoted Commit Id 
      run: |
        echo "$COMMIT_ID" > Promoted_Commit_Id
      env:
        COMMIT_ID: ${{ inputs.promoted_commit_id }}
    - name: Push Promoted Commit Id to GitOps repo
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GITOPS_REPO_TOKEN }}
      with:
        source_file: 'Promoted_Commit_Id'
        destination_repo: ${{ secrets.GITOPS_REPO }}
        destination_folder: '.github/tracking'
        destination_branch: ${{ inputs.environment }}
        user_email: 'agent@gitops.com'
        user_name: 'Git Ops'
        commit_message: 'Promoting Commit_Id from the control plane'
  
  transform:
    needs: promote_to_environment
    uses: ./.github/workflows/transform.yaml
    with:
      promoted_commit_id: ${{ inputs.promoted_commit_id }}
      environment: ${{ inputs.environment }}
    secrets: inherit
