name: checkpromote

on:
  workflow_dispatch:
    inputs:
      promoted_commit_id:
        description: 'Promoted Commit Id from Main'
        required: false
        type: string
      environment:
        required: true
        type: string

jobs:
  wait_for_deployment:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps: 

    - name: Wait for deployment to complete   
      run: |
          echo "Waiting..."

  post_deployment_activities:
    needs: wait_for_deployment
    runs-on: ubuntu-latest
    steps: 

    - name: Run postdeployment activities   
      run: |
          echo "Runinig..."

  # promote_to_next_environment:
  #   if: inputs.promoted_commit_id != ''
  #   needs: post_deployment_activities
  #   uses: ./.github/workflows/cd.yaml
  #   with:
  #     promoted_commit_id: ${{ inputs.promoted_commit_id }}
  #     environment: ${{ inputs.environment }}

