name: checkpromote

on:
  workflow_dispatch:
    inputs:
      promoted_commit_id:
        description: 'Promoted Commit Id from Main'
        required: false
        type: string
      environment:
        required: true
        type: string

jobs:
  wait_for_deployment:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps: 

    - name: Wait for deployment to complete   
      run: |
          echo "Waiting..."

    - name: Get Next Environment
      id: get_next_environment    
      run: |
          echo "::set-output name=next_environment::$NEXT_ENVIRONMENT""
      env:
       NEXT_ENVIRONMENT: ${{ secrets.NEXT_ENVIRONMENT }}

    outputs:
        next_environment: ${{ steps.get_next_environment.next_environment }}


  post_deployment_activities:
    needs: wait_for_deployment
    runs-on: ubuntu-latest
    steps: 

    - name: Run postdeployment activities   
      run: |
          echo "Runinig..."

  # promote_to_next_environment:
  #   needs: wait_for_deployment
  #   runs-on: ubuntu-latest
  #   steps: 

  #   - name: Promote to next environment   
  #     run: |
  #         echo "Promoting..."

  promote_to_next_environment:
    if: inputs.promoted_commit_id != '' && needs.wait_for_deployment.outputs.next_environment != ''
    needs: wait_for_deployment, post_deployment_activities
    uses: ./.github/workflows/cd.yaml
    with:
      promoted_commit_id: ${{ inputs.promoted_commit_id }}
      environment: ${{ needs.wait_for_deployment.outputs.next_environment }}

