name: checkpromote

on:
  workflow_dispatch:
    inputs:
      promoted_commit_id:
        description: 'Promoted Commit Id from Main'
        required: false
        type: string
      environment:
        required: true
        type: string

jobs:
  check_and_promote:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    # env:
    #   NEXT_ENVIRONMENT: ${{ secrets.NEXT_ENVIRONMENT }}
    steps: 

    - name: Wait for deployment to complete   
      run: |
          echo "Waiting..."
          echo "Next Environment: $NEXT_ENVIRONMENT"

    - name: Checkout Source
      uses: actions/checkout@v2.3.4

    - name: Run postdeployment activities   
      run: |
          echo "Runinig..."

    - name: Start CD
      if: inputs.promoted_commit_id != '' && env.NEXT_ENVIRONMENT != ''
      run: |
          gh workflow run cd.yaml -f environment=$NEXT_ENVIRONMENT -f promoted_commit_id=$GITHUB_SHA      
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NEXT_ENVIRONMENT: ${{ secrets.NEXT_ENVIRONMENT }}
        PROMOTED_COMMIT_ID: ${{ inputs.promoted_commit_id }}
        



    # - name: Get Next Environment
    #   id: get_next_environment    
    #   run: |
    #       echo "::set-output name=next_environment::$NEXT_ENVIRONMENT"
    #       echo "Next Environment: $NEXT_ENVIRONMENT"
    #   env:
    #    NEXT_ENVIRONMENT: ${{ secrets.NEXT_ENVIRONMENT }}

    # outputs:
    #     # next_environment: ${{ steps.get_next_environment.outputs.next_environment }}
    #     next_environment: ${{ env.NEXT_ENVIRONMENT }}


  # post_deployment_activities:
  #   needs: wait_for_deployment
  #   runs-on: ubuntu-latest
  #   steps: 


  # cd:
  #   if: inputs.promoted_commit_id != '' && needs.wait_for_deployment.outputs.next_environment != ''
  #   needs: [wait_for_deployment, post_deployment_activities]
  #   uses: ./.github/workflows/cd.yaml
  #   with:
  #     promoted_commit_id: ${{ inputs.promoted_commit_id }}
  #     environment: ${{ needs.wait_for_deployment.outputs.next_environment }}

