name: ci

on:
  push:
    branches:
      - main

jobs:
  Do_Checks:
    runs-on: ubuntu-latest
    steps:    
    - name: Do Some Checks
      run: |
          echo "Do Some Checks"
 
  # Start_CD:
  #   needs: Do_Checks
  #   uses: ./.github/workflows/cd.yaml
  #   with:
  #     promoted_commit_id: ${{ github.sha }}
  #     environment: dev
  #   secrets: inherit

  Start_CD:
    needs: Do_Checks
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout Source
      uses: actions/checkout@v2.3.4
    - name: Start CD
      run: |
          gh workflow run cd.yml -f environment=dev -f promoted_commit_id=$GITHUB_SHA      
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  

