name: ci

on:
  push:
    branches:
      - main

jobs:
  Do_Checks:
    runs-on: ubuntu-latest
    steps:
    - name: Do Some Checks
      run: |
          echo "Do Some Checks"
 
  Start_CD:
    runs-on: ubuntu-latest
    needs: Do_Checks
    steps:
    - name: Promote To Dev
      uses: ./.github/workflows/cd.yml
      with:
        promoted_commit_id: ${{ env.GITHUB_SHA }}
        environment: dev

