name: ci

on:
  push:
    branches:
      - main

jobs:
  Do_Checks:
    runs-on: ubuntu-latest
    steps:
    - name: Do Some Checks
      run: |
          echo "Do Some Checks"
 
  Start_CD:
    # runs-on: ubuntu-latest
    needs: Do_Checks
    uses: ./.github/workflows/cd.yaml
    with:
      promoted_commit_id: ${{ github.sha }}
      environment: dev

