name: transform

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  transform:
    uses: microsoft/kalypso-control-plane/.github/workflows/transform.yaml@main
    with:
      environment: ${{ github.ref_name }}
    secrets: inherit  
