name: transform

on:
  workflow_call:
    inputs:
      promoted_commit_id:
        description: 'Promoted Commit Id from Main'
        required: false
        type: string
      environment:
        required: true
        type: string

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Configs
      uses: actions/checkout@v2.3.4
      with:
        ref: ${{ inputs.environment }}
        path: configs        
    
    - name: Checkout GitOps
      uses: actions/checkout@v2.3.4
      with:
        repository: ${{ secrets.GITOPS_REPO }}
        token: ${{ secrets.GITOPS_REPO_TOKEN }}
        ref: ${{ inputs.environment }}
        path: gitops

    - name: Get Promoted Commit Id 
      working-directory: ${{ github.workspace }}
      run: |
          PROMOTED_COMMIT_ID=$(cat gitops/.github/tracking/Promoted_Commit_Id)
          echo "PROMOTED_COMMIT_ID=$PROMOTED_COMMIT_ID" >> $GITHUB_ENV               

    - name: Checkout Main
      uses: actions/checkout@v2.3.4
      with:
        ref: ${{ env.PROMOTED_COMMIT_ID }} 
        path: main


    - name: Transform 
      working-directory: ${{ github.workspace }}
      run: |                    
          # ls -ltr
          # yq --help
          # echo "Manifests are generated for $PROMOTED_COMMIT_ID commit" > gitops/manifests-statement.txt          
          ${{ github.workspace }}/main/.github/workflows/utils/transform.sh "main/workloads/hello-world-app.yaml" "main/templates/arc-flux-reconciler.yaml" > gitops/drone/workloads/hello-world-app/reconciler.yaml
      env:
        TOKEN: ${{ secrets.GITOPS_REPO_TOKEN }}

    - name: Create PR
      run: |        
        promoted=$([ -z "$COMMIT_ID" ] || echo "promoted")
        ${{ github.workspace }}/main/.github/workflows/utils/create-pr.sh -s ${{ github.workspace }}/gitops -r "https://github.com/"${{ secrets.GITOPS_REPO }} -b ${{ inputs.environment }} -i ${{ github.run_number }} -t ${{ secrets.GITOPS_REPO_TOKEN }} -e ${{ inputs.environment }} -l $promoted
      env:
        COMMIT_ID: ${{ inputs.promoted_commit_id }}

    - name: Update Positive Commit Status
      run: |
          ${{ github.workspace }}/main/.github/workflows/utils/update-status.sh "pending" "Created a PR" "$ENVIRONMENT environment"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PROMOTED_COMMIT_ID: ${{ inputs.promoted_commit_id }}
        ENVIRONMENT: ${{ inputs.environment }}          


    - name: Update Negative Commit Status
      if: ${{ failure() }}    
      run: |
          ${{ github.workspace }}/main/.github/workflows/utils/update-status.sh "failure" "Failed to create a PR" "$ENVIRONMENT environment"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PROMOTED_COMMIT_ID: ${{ inputs.promoted_commit_id }}
        ENVIRONMENT: ${{ inputs.environment }}          


