name: transform

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  transform:
    uses: ${{ github.repository }}/.github/workflows/transform.yaml@main
    with:
      environment: ${{ github.ref_name }}
    secrets: inherit  
