name: transform

on:
  workflow_call:
    inputs:
      promoted_commit_id:
        description: 'Promoted Commit Id from Main'
        required: false
        type: string
      environment:
        description: 'Environment to run tests against'
        required: true
        type: string
  push:
    branches:
      - dev

  
env:
  ENVIRONMENT: fromJSON('["danger", inputs.environment]')[github.event.action == 'workflow_call']

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
    - name: Run Transformation Flow 
      run: |
        echo "Env: $ENVIRONMENT"

    # - name: Checkout Configs
    #   uses: actions/checkout@v2.3.4
    #   with:
    #     ref: dev-configs
    #     path: configs        
    # - name: Checkout Main
    #   uses: actions/checkout@v2.3.4
    # - name: Checkout Configs
    #   uses: actions/checkout@v2.3.4
    #   with:
    #     ref: dev-configs
    #     path: configs        

  
  # transform:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Run Transformation Flow 
  #     run: |
  #       echo "Promoted_Commit_Id: $COMMIT_ID" > Promoted_Commit_Id.yaml
  #     env:
  #       COMMIT_ID: ${{ inputs.promoted_commit_id }}
  #   - name: Push Promoted Commit Id to GitOps repo
  #     uses: dmnemec/copy_file_to_another_repo_action@main
  #     env:
  #       API_TOKEN_GITHUB: ${{ secrets.GITOPS_REPO_TOKEN }}
  #     with:
  #       source_file: 'Promoted_Commit_Id.yaml'
  #       destination_repo: ${{ secrets.GITOPS_REPO }}
  #       destination_folder: '.github/tracking'
  #       destination_branch: ${{ inputs.environment }}
  #       user_email: 'agent@gitops.com'
  #       user_name: 'Git Ops'
  #       commit_message: 'Promoting Commit_Id from the control plane'
