name: transform

on:
  workflow_call:
    inputs:
      promoted_commit_id:
        description: 'Promoted Commit Id from Main'
        required: false
        type: string
      environment:
        description: 'Environment to run tests against'
        required: true
        type: string

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Configs
      uses: actions/checkout@v2.3.4
      with:
        ref: ${{ inputs.environment }}
        path: configs        
    
    - name: Checkout GitOps
      uses: actions/checkout@v2.3.4
      with:
        repository: ${{ secrets.GITOPS_REPO }}
        token: ${{ secrets.GITOPS_REPO_TOKEN }}
        ref: ${{ inputs.environment }}
        path: gitops

    - name: Get Promoted Commit Id 
      working-directory: ${{ github.workspace }}
      run: |
          PROMOTED_COMMIT_ID=$(cat gitops/.github/tracking/Promoted_Commit_Id)
          echo "PROMOTED_COMMIT_ID=$PROMOTED_COMMIT_ID" >> $GITHUB_ENV     

    - name: Checkout Main
      uses: actions/checkout@v2.3.4
      with:
        ref: ${{ env.PROMOTED_COMMIT_ID }} 

    - name: Generate Manifests 
      working-directory: ${{ github.workspace }}
      run: |          
          mkdir manifests
          echo "Manifests are generated for $PROMOTED_COMMIT_ID commit" >> gitops/manifests-statement.txt

    - name: Create PR
      run: |        
        .github/workflows/utils//create-pr.sh -s ${{ github.workspace }}/gitops -d . -r "https://github.com/"${{ secrets.GITOPS_REPO }} -b ${{ inputs.environment }} -i ${{ github.run_number }} -t ${{ secrets.GITOPS_REPO_TOKEN }} -e ${{ inputs.environment }} -l promoted


